version: '3.8'

services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3309
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=testdb

  db:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=testdb
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  k6:
    image: grafana/k6:latest
    volumes:
      - ./k6:/scripts
    depends_on:
      - app

volumes:
  db_data: